"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
require("amis");
require("./locale/index");
tslib_1.__exportStar(require("amis-editor-core"), exports);
tslib_1.__exportStar(require("./builder"), exports);
require("./tpl/index");
tslib_1.__exportStar(require("./plugin"), exports);
require("./renderer/OptionControl");
require("./renderer/NavSourceControl");
require("./renderer/NavBadgeControl");
require("./renderer/NavDefaultActive");
require("./renderer/MapSourceControl");
require("./renderer/TimelineItemControl");
require("./renderer/APIControl");
require("./renderer/APIAdaptorControl");
require("./renderer/ValidationControl");
require("./renderer/ValidationItem");
require("./renderer/SwitchMoreControl");
require("./renderer/StatusControl");
require("./renderer/FormulaControl");
require("./renderer/ExpressionFormulaControl");
require("./renderer/textarea-formula/TextareaFormulaControl");
require("./renderer/TplFormulaControl");
require("./renderer/DateShortCutControl");
require("./renderer/BadgeControl");
require("./renderer/style-control/BoxModel");
require("./renderer/style-control/Font");
require("./renderer/style-control/Border");
require("./renderer/style-control/BoxShadow");
require("./renderer/style-control/Background");
require("./renderer/style-control/Display");
require("./renderer/style-control/InsetBoxModel");
require("./renderer/RangePartsControl");
require("./renderer/DataBindingControl");
require("./renderer/DataMappingControl");
require("./renderer/DataPickerControl");
require("./renderer/FeatureControl");
require("./renderer/event-control/index");
require("./renderer/TreeOptionControl");
require("./renderer/TransferTableControl");
require("./renderer/style-control/ThemeCssCode");
require("./renderer/ButtonGroupControl");
require("./renderer/FlexSettingControl");
require("./renderer/FieldSetting");
require("./renderer/TableColumnWidthControl");
require("./renderer/crud2-control/CRUDColumnControl");
require("./renderer/crud2-control/CRUDToolbarControl");
require("./renderer/crud2-control/CRUDFiltersControl");
require("amis-theme-editor/lib/locale/zh-CN");
require("amis-theme-editor/lib/locale/en-US");
require("amis-theme-editor/lib/renderers/Border");
require("amis-theme-editor/lib/renderers/ColorPicker");
require("amis-theme-editor/lib/renderers/Font");
require("amis-theme-editor/lib/renderers/PaddingAndMargin");
require("amis-theme-editor/lib/renderers/Radius");
require("amis-theme-editor/lib/renderers/Shadow");
require("amis-theme-editor/lib/renderers/Size");
require("amis-theme-editor/lib/renderers.css");
tslib_1.__exportStar(require("./component/BaseControl"), exports);
tslib_1.__exportStar(require("./icons/index"), exports);
